### ISSUE TITLE
referenceBehavior option not working?

### ISSUE THREAD

**Issue by DaveKeehl** [sanity-io/document-internationalization#50]
Hi,

I tried changing the type of referenceBehavior from strong to weak, so that according to the documentation I would have been able to remove the translations. However, it doesn't seem to be working, as I don't see any option regarding this anywhere in the studio.

Has someone been able to get this behavior to work?

**Comment by CodeAlb** [comment]
Yes, but I did on a new studio I am working on.

Did you changed in the config file?
`/config/@sanity/document-internationalization.json`:
```
{
  "referenceBehavior": "weak",
}
```

Maybe this happens because in the database the reference is still `strong`.
After changing the config, try to update each translated document and see if it get changed to `weak`.

**Comment by LiamMartens** [comment]
@DaveKeehl changing the option doesn't automatically update all existing references - the config only applies to new options. If you want to change reference behavior of all existing documents you set the config and try using the [Translation Maintenance](https://github.com/sanity-io/document-internationalization/blob/main/docs/translation-maintenance.md) feature (this has to be enabled)

**Comment by DaveKeehl** [comment]
@CodeAlb @LiamMartens yes I had set that option in the config file, but I didn't check on new translated documents so it must be for sure what you both pointed out. I'll also try out the translation maintenance feature soon, it looks very useful!
